//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherTable
    {
        public int CityId { get; set; }
        public string CityName { get; set; }
        public string Country { get; set; }
        public Nullable<double> Temp { get; set; }
        public Nullable<double> Temp_max { get; set; }
        public Nullable<double> Temp_min { get; set; }
        public Nullable<double> Pressure { get; set; }
        public Nullable<int> Humidity { get; set; }
        public Nullable<decimal> Sunrise { get; set; }
        public Nullable<decimal> Sunset { get; set; }
        public Nullable<decimal> Date_Time { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> Clouds { get; set; }
    }
}
